using Microsoft.AspNet.Identity;
//using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;

namespace TheLibraryIsOpen.Models.DBModels
{
    public class Book 
    {
        public int BookId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Format { get; set; }
        public int Pages { get; set; }
        public string Publisher { get; set; }
        public string Year { get; set; }
        public string Language { get; set; }
        public string Isbn10 { get; set; }
        public string Isbn13 { get; set; }

        // Default constructor
        public Book() { }

        /* Here the constructor assign values to attributes besides BookId.
         * The BookId is generated by database, when insert an entry to the "book" table (assumed it's already & primary key autoincrement).
         * The last id just entered from table would be assigned to BookId for the book object. So that to avoid same id appears when server gets restarted.
        */
        public Book(string title, string author, string format, int pages, string publisher, string year, string language, string isbn10, string isbn13)
        {
            Title = title;
            Author = author;
            Format = format;
            Pages = pages;
            Publisher = publisher;
            Year = year;
            Language = language;
            Isbn10 = isbn10;
            Isbn13 = isbn13;
        }

        // another construcor who  assigns client id is added as requested.
        public Book(int bId, string title, string author, string format, int pages, string publisher, string year, string language, string isbn10, string isbn13)
        { 
            BookId = bId;
            Title = title;
            Author = author;
            Format = format;
            Pages = pages;
            Publisher = publisher;
            Year = year;
            Language = language;
            Isbn10 = isbn10;
            Isbn13 = isbn13;
        }

        // Return information about the music
        public override string ToString()
        {
            return "Book:\nBook ID:" + BookId+ "\nTitle:" + Title + "\nAuthor: " + Author+ "\nFormat:" + Format + "\nPages:" + Pages+ "\nPublisher:" + Publisher + "\nYear:" + Year +
                "\nLanguage:" + Language  + "\nISBN10:" + Isbn10 + "\nISBN13:" + Isbn13 + "\nBook ID:" + BookId;
        }
    }
}
