namespace TheLibraryIsOpen.Models.DBModels
{
    public class Movie
    {
        public int MovieId { get; set; }
        public string MovieName { get; set; }
        public string Genre { get; set; }
        public string Rating { get; set; }
        public string Director { get; set; }
        public int Year { get; set; }
        public string Isbn { get; set; }

        // Default constructor
        public Movie() { }

        /* Here the constructor assign values to attributes besides MovieId.
         * The MovieId is generated by database, when insert an entry to the "movie" table (assumed it's already & primary key autoincrement).
         * The last id just entered from table would be assigned to MovieId for the movie object. So that to avoid same id appears when server gets restarted.
        */
        public Movie(string movieName, string genre, string rating, string director, int year, string isbn)
        {
            MovieName = movieName;
            Genre = genre;
            Rating = rating;
            Director = director;
            Year = year;
            Isbn = isbn;
        }

        // another construcor who  assigns client id is added as requested.
        public Movie(int mvId, string movieName, string genre, string rating, string director, int year, string isbn)
        {
            MovieId = mvId;
        }

        // Return information about the music
        public override string ToString()
        {
            return "Movie:\nMovie Name:" + MovieName + "\nGenre:" + Genre + "\nRating: " + Rating + "\nDirected By:" + Director + "\nYear:" + Year + "\nISBN:" + Isbn + "\nMovie ID:" + MovieId;
        }
    }
}
