using System.ComponentModel.DataAnnotations.Schema;

namespace TheLibraryIsOpen.Models.DBModels
{
    public class Person
    {
        public int PersonId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        [NotMapped]
        public string FullName { get => $"{FirstName} {LastName}"; }

        // Default constructor
        public Person() { }

        /* Here the constructor assign values to attributes besides personId.
         * The personID is generated by database, when insert an entry to the "person" table (assumed it's already & primary key autoincrement).
         * The last id just entered from table would be assigned to personId for the person object. So that to avoid same id appears when server gets restarted.
        */
        public Person(string firstName, string lastName)
        {
            FirstName = firstName;
            LastName = lastName;

        }

        // another construcor who  assigns person id is added as requested.
        public Person(int pId, string firstName, string lastName)
        {
            PersonId = pId;
            FirstName = firstName;
            LastName = lastName;
           
        }

        // Return information about the person
        public override string ToString()
        {
            return "Person:\nFirst Name:" + FirstName + "\nLast Name:" + LastName + "\nPerson ID:" + PersonId;
        }

    }
}
